name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-articles:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update articles
        uses: huantt/article-listing@v1.1.0
        with:
          username: khaleo
          template-file: "README.md.template"
          out-file: "README.md"
          limit: 5
      - name: Check for changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update articles"
            git push origin main
          else
            echo "No changes to commit. Exiting gracefully."
          fi

  devcard:
    needs: update-articles
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
